meta_product_name: "Product Name"
meta_title: "Product name - Product tagline"
meta_description: "Relevant description"
meta_image: "http://res.cloudinary.com/dgzpma7qs/image/upload/c_scale,h_630,w_1200/v1501007201/pjaexkwcjapysrbvrxqh.png"
